In [2]:
import numpy as np

#### ADDITION OF TWO VECTORS/MATRICES

In [2]:
a=np.array([[10,15]])
b=np.array([[20,9]])
print(a)
print(b)
print()
(a+b).T

[[10 15]]
[[20  9]]



array([[30],
       [24]])

In [5]:
(a+b)

array([[30, 24]])

#### SUBTRACTING TWO VECTORS/MATRICES

In [3]:
(a-b).T

array([[-10],
       [  6]])

In [4]:
(a-b)

array([[-10,   6]])

#### SCALAR MULTIPLICATION

In [10]:
a=2
u=np.array([[30,15]])
print(a*u)
(a*u).T

[[60 30]]


array([[60],
       [30]])

#### DOT PRODUCT OF 2 VECTORS; FOR 2D VECTORS, IT IS EQUIVALENT TO MATRIX MULTIPLICATION

In [12]:
u = np.array([10,20])
v = np.array([25,6])
print(10 *25 + 20 * 6)
np.dot(u,v)

370


370

#### MATRIX ADDITION

In [6]:
a = np.array([[12,10],[4,6],[40,31],])
b = np.array([[2,8],[46, 63],[50,10],])
print(a,end=" = a\n\n")
print(b, end=" = b\n\n")

a+b

[[12 10]
 [ 4  6]
 [40 31]] = a

[[ 2  8]
 [46 63]
 [50 10]] = b



array([[14, 18],
       [50, 69],
       [90, 41]])

#### MATRIX SUBTRACTION

In [7]:
a-b

array([[ 10,   2],
       [-42, -57],
       [-10,  21]])

#### MATRIX SCALAR MULTIPLICATION

In [3]:
a = 4
b = np.array([[2,5],[3,7],[8,6]])
a*b

array([[ 8, 20],
       [12, 28],
       [32, 24]])

#### MATRIX AND VECTOR MULTIPLICATION

In [4]:
a = [[5,10],[15,20]]
b = [10,12]
np.dot(a,b)

array([170, 390])

#### TRANSPOSE OF A MATRIX

In [5]:
a = np.array([[5,10],[15,20],[25,30]])
print(a,end=" = a\n\n")
print(a.T, end = " = aT")


[[ 5 10]
 [15 20]
 [25 30]] = a

[[ 5 15 25]
 [10 20 30]] = aT

#### IDENTITY MATRIX

In [6]:
I1 = np.eye(2)
I2 = np.eye(3)
print(I1, end=" = I1\n\n")
print(I2, end=" = I2\n\n")

[[1. 0.]
 [0. 1.]] = I1

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] = I2



#### INVERSE MATRIX - Given a square matrix A return the matrix A inverse satisfying dot(a,a inverse) = dot(a inverse, a) = eye(a.shape[0])

In [7]:
a = np.array([[2,1,0],[0,1,0],[1,2,1]])
print(a, end=" = a\n\n")
print(np.linalg.inv(a),end = " =|a|")

[[2 1 0]
 [0 1 0]
 [1 2 1]] = a

[[ 0.5 -0.5  0. ]
 [ 0.   1.   0. ]
 [-0.5 -1.5  1. ]] =|a|